@startuml

hide empty description

title HazardZone State Diagram

[*] --> Inactive

'------------------------------------------------------------------------------
' Inactive (ZoneState=Inactive, AlarmState=None)
'------------------------------------------------------------------------------

Inactive : ZoneState = Inactive
Inactive : AlarmState = None

Inactive --> Activating : ManuallyActivate()\n[activationDuration > 0]
Inactive --> Activating : ActivateFromExternalSource(source ID)\n[source ID unknown]\n[activationDuration > 0]
Inactive --> Active : ManuallyActivate()\n[activationDuration == 0]
Inactive --> Active : ActivateFromExternalSource(source ID)\n[source ID unknown]\n[activationDuration == 0]

'------------------------------------------------------------------------------
' Activating (ZoneState=Activating, AlarmState=None)
'------------------------------------------------------------------------------

Activating : ZoneState = Activating
Activating : AlarmState = None
Activating : entry / RaiseHazardZoneActivationStarted()
Activating : entry / StartActivationTimer()

Activating --> Activating : OnPersonAdded()
Activating --> Activating : OnPersonRemoved()
Activating --> Active : OnActivationTimerElapsed()
Activating --> Inactive : ManuallyDeactivate()
Activating --> Inactive : DeactivateFromExternalSource(source ID)\n[source ID known]

'------------------------------------------------------------------------------
' Active (ZoneState=Active, AlarmState=None)
'------------------------------------------------------------------------------

Active : ZoneState = Active
Active : AlarmState = None

Active --> Active : OnPersonAdded()\n[numberOfPersons <= allowedNumberOfPersons]
Active --> Active : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons <= allowedNumberOfPersons]
Active --> Active : DeactivateFromExternalSource(source ID)\n[source ID unknown]
Active --> PreAlarm : OnPersonAdded()\n[numberOfPersons > allowedNumberOfPersons]\n[preAlarmDuration > 0]
Active --> PreAlarm : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons > allowedNumberOfPersons]\n[preAlarmDuration > 0]
Active --> Alarm : OnPersonAdded()\n[numberOfPersons > allowedNumberOfPersons]\n[preAlarmDuration == 0]
Active --> Alarm : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons > allowedNumberOfPersons]\n[preAlarmDuration == 0]
Active --> Inactive : ManuallyDeactivate()
Active --> Inactive : DeactivateFromExternalSource(source ID)\n[source ID known]

'------------------------------------------------------------------------------
' PreAlarm (ZoneState=Active, AlarmState=PreAlarm)
'------------------------------------------------------------------------------

PreAlarm : ZoneState = Active
PreAlarm : AlarmState = PreAlarm

PreAlarm --> PreAlarm : RemovePerson()\n[numberOfPersons > allowedNumberOfPersons]
PreAlarm --> PreAlarm : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons > allowedNumberOfPersons]
PreAlarm --> PreAlarm : DeactivateFromExternalSource(source ID)\n[source ID unknown]
PreAlarm --> Active : RemovePerson()\n[numberOfPersons <= allowedNumberOfPersons]
PreAlarm --> Active : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons <= allowedNumberOfPersons]
PreAlarm --> Alarm : OnPreAlarmTimerElapsed()
PreAlarm --> Inactive : ManuallyDeactivate()
PreAlarm --> Inactive : DeactivateFromExternalSource(source ID)\n[source ID known]

'------------------------------------------------------------------------------
' Alarm (ZoneState=Active, AlarmState=Alarm)
'------------------------------------------------------------------------------

Alarm : ZoneState = Active
Alarm : AlarmState = Alarm

Alarm --> Alarm : RemovePerson()\n[numberOfPersons > allowedNumberOfPersons]
Alarm --> Alarm : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons > allowedNumberOfPersons]
Alarm --> Alarm : DeactivateFromExternalSource(source ID)\n[source ID unknown]
Alarm --> Active : RemovePerson()\n[numberOfPersons <= allowedNumberOfPersons]
Alarm --> Active : SetAllowedNumberOfPersons(allowedNumberOfPersons)\n[numberOfPersons <= allowedNumberOfPersons]
Alarm --> Inactive : ManuallyDeactivate()
Alarm --> Inactive : DeactivateFromExternalSource(source ID)\n[source ID known]

@enduml